import net.sf.jasperreports.engine.*;


public class FSLS02Scriptlet extends JRDefaultScriptlet {
    
/** Creates a new instance of JRIreportDefaultScriptlet */
public FSLS02Scriptlet() {
	
	
}
public String iseng(double number){
	String terbilang=this.generate(number);
	sb.delete(0,sb.length());
	return terbilang;
}
	String bilangan[] = new String[] { "", "SATU ", "DUA ", "TIGA ", "EMPAT ",
 		"LIMA ", "ENAM ", "TUJUH ", "DELAPAN ", "SEMBILAN ", "SEPULUH ",
 		"SEBELAS " };
	private StringBuffer sb = new StringBuffer();

	public String generate(double number) {

		if (number < 12) {
 		sb.append(bilangan[(int)number]);
 	}

		if (number >= 12 && number < 20) {
 		generate( number - 10);
 		sb.append("BELAS ");
 	}

		if(number >= 20 && number < 100){
 		generate(number/10);
 		sb.append("PULUH ");
 		generate(number % 10);
 	}

		if (number >= 100 && number < 200) {
 		sb.append("SERATUS ");
 		generate( number % 100 );
 	}

		if (number >= 200 && number < 1000){
 		generate(number / 100);
 		sb.append("RATUS ");
 		generate( number % 100 );
 	}

		if (number >= 1000 && number < 2000){
 		sb.append("SERIBU ");
 		generate( number % 1000 );
 	}

		if(number >= 2000 && number < 1000000){
 		generate(number/1000);
 		sb.append("RIBU ");
 		generate( number % 1000);
 	}

		if (number >= 1000000 && number < 1000000000){
 		generate(number/1000000);
 		sb.append("JUTA ");
 		generate( number % 1000000 );
 	}

		return sb.toString();
 }













/** Begin EVENT_AFTER_COLUMN_INIT This line is generated by iReport. Don't modify or move please! */
public void afterColumnInit() throws JRScriptletException
{
	super.beforeColumnInit();
}
/** End EVENT_AFTER_COLUMN_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_AFTER_DETAIL_EVAL This line is generated by iReport. Don't modify or move please! */
public void afterDetailEval() throws JRScriptletException
{
	super.afterDetailEval();
}
/** End EVENT_AFTER_DETAIL_EVAL This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_AFTER_GROUP_INIT This line is generated by iReport. Don't modify or move please! */
public void afterGroupInit(String groupName) throws JRScriptletException
{
	super.afterGroupInit(groupName);
}
/** End EVENT_AFTER_GROUP_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_AFTER_PAGE_INIT This line is generated by iReport. Don't modify or move please! */
public void afterPageInit() throws JRScriptletException
{
	super.afterPageInit();
}
/** End EVENT_AFTER_PAGE_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_AFTER_REPORT_INIT This line is generated by iReport. Don't modify or move please! */
public void afterReportInit() throws JRScriptletException
{
	
}
/** End EVENT_AFTER_REPORT_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_COLUMN_INIT This line is generated by iReport. Don't modify or move please! */
public void beforeColumnInit() throws JRScriptletException
{
		
}
/** End EVENT_BEFORE_COLUMN_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_DETAIL_EVAL This line is generated by iReport. Don't modify or move please! */
public void beforeDetailEval() throws JRScriptletException
{
	
}
/** end EVENT_BEFORE_DETAIL_EVAL Please don't touch or move this comment*/

/** End EVENT_BEFORE_DETAIL_EVAL This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_GROUP_INIT This line is generated by iReport. Don't modify or move please! */
public void beforeGroupInit(String groupName) throws JRScriptletException
{
	
}
/** End EVENT_BEFORE_GROUP_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_PAGE_INIT This line is generated by iReport. Don't modify or move please! */
public void beforePageInit() throws JRScriptletException
{
	
}
/** End EVENT_BEFORE_PAGE_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_REPORT_INIT This line is generated by iReport. Don't modify or move please! */
public void beforeReportInit() throws JRScriptletException
{
	
}

/** End EVENT_BEFORE_REPORT_INIT This line is generated by iReport. Don't modify or move please! */

}